### ISSUE TITLE
Adding React-Router

### ISSUE THREAD

**Issue by daslicht** [piotrwitek/react-ts-jspm-starter-kit#1]
Hi,
I am following this tutorial here : 
https://github.com/reactjs/react-router-tutorial/tree/master/lessons/05-active-links
When I add the following element : 

```
        <Link {...this.props} activeClassName="active"/>
```

I get this Type Error here : 

![](http://i.imgur.com/9RMLdpQ.png)

here is the full code:

```

import * as React from 'react';
// components imports
import {AppStore, UserData} from '../stores/app-store';
import {UserProfile} from './user-profile';
import { Link } from 'react-router'

interface LocalProps extends React.Props<NavLink> {
}

// App pure component
export class NavLink extends React.Component<LocalProps, AppStore> {
  constructor() {
    super();
    this.state = new AppStore();
  }

  render() {
    return (
      <Link {...this.props} activeClassName="active"/>
    );
  }
}

```

I have installed  react-router using jspm and its typings via typings --ambient

**Comment by daslicht** [comment]
I have now added an Interface with the Link Props and the error is gone: 

```

import * as React from 'react';
// components imports
import {AppStore, UserData} from '../stores/app-store';
import {UserProfile} from './user-profile';
import { Link } from 'react-router'

interface LocalProps extends React.Props<NavLink> {
        activeStyle;
        activeClassName;
        onlyActiveOnIndex;
        to;
        query;
        state;
        ref;
}

// App pure component
export class NavLink extends React.Component<LocalProps, AppStore> {
  constructor() {
    super();
    this.props.to;
    this.props.ref;
    this.state = new AppStore();
  }

  render() {
    return (

      <Link { ... this.props } activeClassName="active"/>
    );
  }
}
```

I that the correct way top solve such kind of issue ?

**Comment by piotrwitek** [comment]
Hi @daslicht,
Sorry for my late reply, I haven't setup my repo notifications properly.
I see in your code you are missing declaration of "to" props in you LocalProps interface, then when using NavLink component you have also to add it to your component declaration.

But it is good idea to introduce React Router example into starter-kit, I will try to add it soon.
Cheers.

**Comment by daslicht** [comment]
anything fine ! I will try it again later

**Comment by piotrwitek** [comment]
I have reconsidered this enhancement again, and decided that I won't put it in the master but rather in the branch.

Rationale is that main purpose of this boilerplate is to provide just bare minimum scaffold of project and shouldn't include routing lib as I don't want to handicap devs who don't want to use React-Router or have a preference in other routing library.

**Comment by piotrwitek** [comment]
@daslicht just to let you know React-Router added

**Comment by daslicht** [comment]
nice
