### ISSUE TITLE
Finish demo/examples

### ISSUE THREAD

**Issue by Waterstraal** [piotrwitek/react-ts-jspm-starter-kit#18]
It seems to me that the demo on http://piotrwitek.github.io/react-redux-typescript-starter-kit/ is not working properly. 
- Page **Home**: I don't see a list of projects here as the text "Here you can find real world projects made using this starter-kit." suggests?
- Page **Currency Converter**: The "Currency Converter" isn't converting anything?

**Comment by piotrwitek** [comment]
Sorry, content is not finished yet :)

**Comment by Waterstraal** [comment]
Ah I thought I was missing something haha, thanks :).

Any idea when it will be finished?

**Comment by piotrwitek** [comment]
Yea probably I should write something like WIP :)
Right now I'm going on vacation for 2 weeks without laptop access, but
after my return I'll probably finish it in about 2 weeks.

Pozdrawiam,
Piotr Witek

2016-09-21 11:31 GMT+02:00 Waterstraal notifications@github.com:

**Comment by piotrwitek** [comment]
@Waterstraal added some working example with CSS Modules
added WIP info for currency converter

**Comment by piotrwitek** [comment]
- [ ] fisnish implementing logic for Currency Converter
- [ ] try to implement using redux-observables

**Comment by piotrwitek** [comment]
resolved with #36
