### ISSUE TITLE
Build task should generate a index.html in dist/

### ISSUE THREAD

**Issue by guillaume86** [piotrwitek/react-ts-jspm-starter-kit#20]
I tried to make it work by copying the base index.html and adapting the scripts urls to the ones in /dist/ but app.js failed to load.

Could you generate the proper html (maybe by "patching" the root index.html?) in addition to the js files?

Unrelated:
Thanks for this repo, that starter kit looks really interesting to me, the dev performance aspect in particular.

**Comment by guillaume86** [comment]
You can ignore this, I missed the assets folder... sorry

**Comment by piotrwitek** [comment]
Hi @guillaume86 ,
Cool, no problem but it means that I should update documentation on this, thx for your input.

I could add it to the queue, but right now I have a list of more important features to add.
Contributions are welcome :)

**Comment by guillaume86** [comment]
I'll have to evaluate different frameworks (React/Redux vs Angular2) for my job in a week or two.
I'll probably use your starter kit as a base for the react prototype, I'll contribute if I manage to do useful and clean additions. 

I'm not experienced with the React/Redux/TS combo so I'm not sure I'll be very helpful, but your code is very informative so thanks.

**Comment by piotrwitek** [comment]
Any kind of feedback is valuable for me to improve :) Thanks and good luck
in finding the best solution for your project.

Pozdrawiam,
Piotr Witek

2016-10-06 14:42 GMT+02:00 Guillaume Lecomte notifications@github.com:
