### ISSUE TITLE
strictNullChecks: true by default

### ISSUE THREAD

**Issue by karudo** [piotrwitek/react-ts-jspm-starter-kit#25]
I think, if we use typescript 2, we should set strictNullChecks: true by default. What is your opinion?

**Comment by piotrwitek** [comment]
Yes I would definitely try to switch strictNullChecks because of the benefits it could bring to my code base, though currently I have other things on my plate, I will certainly add it in the future.
Thanks for suggestion.

**Comment by piotrwitek** [comment]
I think I'll do it now with TS 2.1 release, with it's better support for type inference, non-nullable types (when strictNullChecks and noImplicitAny is enabled) will give a huge benefit of better type safety across entire codebase.

**Comment by piotrwitek** [comment]
@karudo done! 7cb59ab453d850ca7c7de822d5222597c0329fe5

**Comment by piotrwitek** [comment]
also greatly improved Store, Reducers, Actions and Props types across the board
