### ISSUE TITLE
cross-platform npm scripts 

### ISSUE THREAD

**Issue by maxali** [piotrwitek/react-ts-jspm-starter-kit#26]
There are some npm scripts that are using Linux special commands like: 
`cp` command in `init:dist`, `regenerator` and `post_jspm-bundle-vendor-prod`.

This will not work in Windows environment. I had to use `Cygwin` tool to use linux commands.

We may create nodejs build file (build.js) which would make use of `fs`, and call it from npm scripts like `node ./build --some arguments`.

Do you have any idea how we can make it cross-platform.

**Comment by piotrwitek** [comment]
@maxali I can look into that in the future, but I'm not using windows so I'll not be able to test it.
If you'd like you can try to create this build script yourself, please submit PR then I'll review it and add it to the project.

**Comment by maxali** [comment]
Submitted PR #27 to solve this.

**Comment by piotrwitek** [comment]
@maxali I have investigated this suggestion and decided I'll rather use https://www.npmjs.com/package/shelljs project instead of proposed ncp.
Other concerns:
- There are `mv` commands that ncp will not resolve, shelljs handle this
- shelljs is more mature
- more versatile

**Comment by piotrwitek** [comment]
I'll rewrite commands entirely as node scripts, to clean up cluttered package.json.

**Comment by piotrwitek** [comment]
@maxali Done: https://github.com/piotrwitek/react-redux-typescript-starter-kit/pull/28
