### ISSUE TITLE
Build version uses jspm_packages folder

### ISSUE THREAD

**Issue by maxali** [piotrwitek/react-ts-jspm-starter-kit#42]
Production build with `npm run build:app` loads modules from `jsmp_packages` folder.
I run `npm run init` and `npm run build:app`. 

![image](https://cloud.githubusercontent.com/assets/1834466/22883441/92a844f6-f1f0-11e6-9cd2-d30ee00499ce.png)

This is the [jspm.config.js](https://github.com/piotrwitek/react-redux-typescript-starter-kit/blob/v0.12.0/jspm.config.js) i am using.

**Comment by piotrwitek** [comment]
I see that browser cannot find vendor.prod.bundle.
This is a bundle that contain all your dependencies, this is why it is looking for jspm_packages as a resolution algorithm

I think if you build with `npm run build` as opposed to only building your app source code, it should resolve your problem. 

Please take a look at docs: https://github.com/piotrwitek/react-redux-typescript-starter-kit#production-bundling-dist-folder

**Comment by piotrwitek** [comment]
@maxali should be closed?

**Comment by maxali** [comment]
@piotrwitek you are right. I had to run `npm run build`.

Sorry for the late reply.
