### ISSUE TITLE
Sass files

### ISSUE THREAD

**Issue by MKHenson** [piotrwitek/react-ts-jspm-starter-kit#56]
Hi piotrwitek. Just wanted to say thanks for this great project - very helpful. 

Would you have any insight into how I could maybe include sass files? So:

    import './main-layout.scss!';

instead of:

    import './main-layout.css!';

Thanks

**Comment by piotrwitek** [comment]
@MKHenson Hello, yes sure :)
please check this plugin: https://github.com/dougludlow/plugin-sass
setting it up should be easy:

here -> https://github.com/piotrwitek/react-redux-typescript-starter-kit/blob/master/jspm.config.js#L74

add this:
```
meta: {
    "*.scss": { "loader": "sass" },
    "*.sass": { "loader": "sass" }
  }
```

for more advanced configuration please check plugin page

**Comment by MKHenson** [comment]
Thanks @piotrwitek , that worked a charm :)
