### ISSUE TITLE
Is there a sample for writing tests with this starter kit ?

### ISSUE THREAD

**Issue by srivathsah** [piotrwitek/react-ts-jspm-starter-kit#57]

**Comment by piotrwitek** [comment]
Here:
testing simple business logic: https://github.com/piotrwitek/react-redux-typescript-starter-kit/blob/master/src/store/currency-converter/utils.spec.tsx
testing store modules (it is not complete, but just follow the [redux testing guide](http://redux.js.org/docs/recipes/WritingTests.html)): https://github.com/piotrwitek/react-redux-typescript-starter-kit/blob/master/src/store/currency-rates/spec/currency-rates-reducer.spec.tsx
