### ISSUE TITLE
I would like to use superagent 

### ISSUE THREAD

**Issue by Benez** [piotrwitek/react-ts-jspm-starter-kit#58]
Dear Piotr Witek,

I love your work and I just started using it, I'm trying to add a middleware in redux using superagent to query a remote API server.

How can I add dependencies correctly?

Thanks a lot for your help.

My best regards,

Stefano Benetti

**Comment by Benez** [comment]
solved 

Thanks :-)

**Comment by piotrwitek** [comment]
👍
