### ISSUE TITLE
How to include Bootstrap 4?

### ISSUE THREAD

**Issue by jakub-astrahit** [piotrwitek/react-ts-jspm-starter-kit#61]
Hi, thanks for this great repo, but what would be the best way to include [Bootstrap 4](https://getbootstrap.com/) please? Add it to assets and then load in loader-styles.css?

**Comment by piotrwitek** [comment]
Hi,
I would add to assets and reference from index.html using link tag

**Comment by jakub-astrahit** [comment]
Yep, it was that simple. Now I look like an idiot 🤣  Thanks for your fast response!
